server:
  port: 9000

spring:
  config:
    activate:
      on-profile: local
    import:
      - application-core-local.yml
  application:
    name: api-gateway-service
  cloud:
    gateway:
#      default-filters:
#        - name : CustomGlobalFilter
      routes:
        #        ...
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*),/$\{path}
        - id: auth-service
          uri: http://localhost:6100
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*),/$\{path}

auth:
  whitelist:
    - path: /auth/sign-in
      method: POST
    - path: /auth/sms/send
      method: POST
    - path: /auth/sms/verify
      method: POST
    - path: /user/sign-up
      method: POST

jwt:
  secret: d60a8f96de19bbb13a5d7b9b4489169d6283856b701d5cd2fce5a9faae85c82730fddc6950f1969e1606c308bd6dfeaa8bfef9aeddcc2073126d458ed2613fe2a011a16df6e8ef963cf587bdc6dff3f2e97ad94232abdd299a0447f8c13238b2d2195888b9e7320d2c3a32c4199be660f8b1e99fef1b84596e7a9533ba9e76656c37176ea7f04cbd1dd0474875caa6e891da910cca2b88c17e537faeec0d0023232472cf677759439aa372c614120eef987f49a7664130c9a920f9f38ba1751c8ef1de5a4171e64bfd00e0c0875ed957de300c26c87334b42f0e59676adb689415c9fbb3adcb102867ee263558a1d1ae2ab3d24c460f5b588eeeb49bab1b7f4e
